version: "3.9"
services:
  db_shortcut:
    image: postgres
    container_name: db_shortcut
    environment:
      - POSTGRES_DB=url_short_cut_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_shortcut/url_short_cut_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortcut
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_shortcut:5432/url_short_cut_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db_shortcut